# Generated by Django 4.2.7 on 2023-11-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designstudio', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('Новая', 'Новая'), ('Принята в работу', 'Принято в работу'), ('Выплнено', 'Выполнено')], default='Новая', max_length=16, verbose_name='Статус'),
        ),
    ]
